window.CINEVAULT_CATALOG=[
{t:'Alpha',y:2026,type:'movie',g:['Action','Spy','Thriller'],pop:100,img:'https://m.media-amazon.com/images/M/MV5BMjUzMGZjMjYtYjRmMy00NWNkLWExMmUtZTc4MDU4NDZmNzcwXkEyXkFqcGc%40._V1_FMjpg_UX1000_.jpg',badge:'#1'},
{t:'The Whisper Man',y:2026,type:'movie',g:['Mystery','Thriller','Crime'],pop:98,img:'https://m.media-amazon.com/images/M/MV5BZDdjOTQzMzEtZjYyOC00MWI0LWJlZDItNDBmMDFmODYxZDk1XkEyXkFqcGc%40._V1_.jpg',badge:'TRENDING'},
{t:'The Secret Woman',y:2026,type:'movie',g:['Drama','Mystery','Thriller'],pop:96,img:'https://images.ctfassets.net/4cd45et68cgf/3mbqqX0cP4YdbTnOVLUt45/9842421100e45de47e3fb543eddb6aac/TheSecretWoman__23A5805_LasseBakMejlvang_Netflix.jpg?w=1000',badge:'NEW'},
{t:'Facing El Chapo',y:2026,type:'movie',g:['Action','Crime','Drama'],pop:97,img:'https://image.tmdb.org/t/p/original/etFPzmqXZlHDderOCgg3YjQswT1.jpg',badge:'#2'},
{t:'Grand Theft Auto VI: An Extended Look',y:2026,type:'movie',g:['Action','Crime','Adventure'],pop:95,img:'https://cdn.bingebase.com/movies/221316/posters/nNYOsrgnIuoZcxXprHJRh5l7y5g.webp',badge:'#3'},
{t:'The Last House',y:2026,type:'movie',g:['Sci-Fi','Thriller','Survival'],pop:94,img:'https://v1.fdbimg.pl/crop?height=1350&noprofile=true&quality=80&sign=FpT5yReI0sZNpxvGrE5VsGB9o-CBKZdmjnlqer162RA&stripmeta=true&type=webp&url=https%3A%2F%2Fi11.fdbimg.pl%2Fi%2Fv%2Fp%2Fx%2Fvpxi5c6qcbta5e27zzgq6lpawyw2&width=931',badge:'#6'},
{t:'Colours of Fire',y:2022,type:'movie',g:['Drama','Historical'],pop:80,img:'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak%3D/v3/t/assets/p23410678_v_v8_ad.jpg',badge:'#4'},
{t:'Cradle 2 the Grave',y:2003,type:'movie',g:['Action','Crime','Martial Arts'],pop:83,img:'https://cdn11.bigcommerce.com/s-yzgoj/images/stencil/1280x1280/products/2878759/5908779/MOVIH8985__92726.1679563278.jpg?c=2',badge:'#5'},
{t:'The Heat',y:2013,type:'movie',g:['Comedy','Action'],pop:82,img:'https://1.bp.blogspot.com/-PlKiXNHLGlk/UnZUNVr5rgI/AAAAAAAADAw/Ohs0pzvi0Xg/s1600/The%2BHeat%2B2013%2Bfilm%2Blarge%2Bmovie%2Bposter%2Bmalaysia.jpg',badge:'#8'},
{t:'Abigail',y:2024,type:'movie',g:['Horror','Thriller'],pop:91,img:'https://s.movieinsider.com/images/p/761142_m1705000562.jpg',badge:'#9'},
{t:'Sniper: The Last Stand',y:2025,type:'movie',g:['Action','Military','Thriller'],pop:90,img:'https://screenanarchy.com/assets/2025/01/DP_9533385_SNIPERTHELASTSTAND_2000x3000LSR_HEKeyArt.jpg',badge:'#10'},
{t:'Inception',y:2010,type:'movie',g:['Sci-Fi','Thriller'],pop:99,img:'https://pics.filmaffinity.com/Inception-131981581-large.jpg'},
{t:'Interstellar',y:2014,type:'movie',g:['Sci-Fi','Adventure','Drama'],pop:98,img:'https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'},
{t:'The Dark Knight',y:2008,type:'movie',g:['Action','Crime','Drama'],pop:99,img:'https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg'},
{t:'Parasite',y:2019,type:'movie',g:['Drama','Thriller'],pop:95,img:'https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg'},
{t:'Titanic',y:1997,type:'movie',g:['Romance','Drama'],pop:97,img:'https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg'},
{t:'The Matrix',y:1999,type:'movie',g:['Sci-Fi','Action'],pop:96,img:'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg'},
{t:'Avatar',y:2009,type:'movie',g:['Sci-Fi','Adventure','Action'],pop:95,img:'https://image.tmdb.org/t/p/original/kmcqlZGaSh20zpTbuoF0Cdn07dT.jpg'},
{t:'Oppenheimer',y:2023,type:'movie',g:['Drama','History'],pop:94,img:'https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'},
{t:'Spider-Man: Into the Spider-Verse',y:2018,type:'movie',g:['Animation','Action','Adventure'],pop:94,img:'https://image.tmdb.org/t/p/original/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg'},
{t:'Dune: Part Two',y:2024,type:'movie',g:['Sci-Fi','Adventure','Action'],pop:97,img:'https://image.tmdb.org/t/p/original/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg'},
{t:'Everything Everywhere All at Once',y:2022,type:'movie',g:['Sci-Fi','Comedy','Action'],pop:92,img:'https://image.tmdb.org/t/p/original/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg'},
{t:'The Lord of the Rings: The Fellowship of the Ring',y:2001,type:'movie',g:['Fantasy','Adventure','Action'],pop:98,img:'https://image.tmdb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkbl1cHo6.jpg'},
{t:'The Godfather',y:1972,type:'movie',g:['Crime','Drama'],pop:98,img:'https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg'},
{t:'Pulp Fiction',y:1994,type:'movie',g:['Crime','Drama','Thriller'],pop:97,img:'https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg'},
{t:'Spirited Away',y:2001,type:'movie',g:['Animation','Fantasy','Adventure'],pop:95,img:'https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg'},
{t:'Mad Max: Fury Road',y:2015,type:'movie',g:['Action','Adventure','Sci-Fi'],pop:96,img:'https://image.tmdb.org/t/p/original/hA2ple9q4qnwxp3hKVNhroipsir.jpg'},
{t:'Get Out',y:2017,type:'movie',g:['Horror','Mystery','Thriller'],pop:94,img:'https://image.tmdb.org/t/p/original/tFXcEccSQMf3lfhf4yHf9f1b6mH.jpg'},
{t:'Top Gun: Maverick',y:2022,type:'movie',g:['Action','Drama'],pop:96,img:'https://image.tmdb.org/t/p/original/62HCnUTziyWcpDaBO2i1DX17ljH.jpg'},
{t:'Black Panther',y:2018,type:'movie',g:['Action','Superhero','Adventure'],pop:95,img:'https://image.tmdb.org/t/p/original/uxzzxijgPIY7slzFvMotPv8wjKA.jpg'},
{t:'Avengers: Endgame',y:2019,type:'movie',g:['Action','Superhero','Adventure'],pop:99,img:'https://image.tmdb.org/t/p/original/or06FN3Dka5tukK1e9sl16pB3iy.jpg'},
{t:'The Shawshank Redemption',y:1994,type:'movie',g:['Drama'],pop:99,img:'https://image.tmdb.org/t/p/original/lyQBXzOQTgK6J6H8m4u8YfQfF7Q.jpg'},
{t:'Gladiator',y:2000,type:'movie',g:['Action','Drama','Adventure'],pop:95,img:'https://image.tmdb.org/t/p/original/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg'},
{t:'The Lion King',y:1994,type:'movie',g:['Animation','Family','Adventure'],pop:97,img:'https://image.tmdb.org/t/p/original/2e853FDVSIso600tD7t8K0d5D6T.jpg'},
{t:'Jurassic Park',y:1993,type:'movie',g:['Adventure','Sci-Fi','Action'],pop:96,img:'https://image.tmdb.org/t/p/original/fjTU1Bgh3KJu4GQj7Gf7G5m8Y9d.jpg'},
{t:'Coco',y:2017,type:'movie',g:['Animation','Family','Fantasy'],pop:94,img:'https://image.tmdb.org/t/p/original/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg'},
{t:'2012',y:2009,type:'movie',g:['Action','Disaster','Sci-Fi'],pop:86,img:'https://www.westsideseattle.com/sites/default/files/styles/news_teaser/public/images/www.westseattleherald.com/2010/01/2012_poster.jpg?itok=o-0zILyx'},
{t:'The Suicide Squad',y:2021,type:'movie',g:['Action','Comedy','Superhero'],pop:89,img:'https://es.web.img3.acsta.net/pictures/21/03/29/11/37/4173669.jpg'},
{t:'The Fall Guy',y:2024,type:'movie',g:['Action','Comedy','Romance'],pop:92,img:'https://artofthemovies.co.uk/cdn/shop/files/IMG_5710-1.jpg?v=1708180802'},
{t:'Lionheart',y:2018,type:'movie',g:['Drama','Comedy','Nigeria','African Cinema'],pop:90,img:'https://cdn.guardian.ng/wp-content/uploads/2019/03/Genevieve.jpg',badge:'NIGERIA'},
{t:'A Tribe Called Judah',y:2023,type:'movie',g:['Comedy','Drama','Nigeria','African Cinema'],pop:91,img:'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak%3D/v3/t/assets/p26320013_p_v8_aa.jpg',badge:'NIGERIA'},
{t:'Living in Bondage: Breaking Free',y:2019,type:'movie',g:['Drama','Thriller','Nigeria','African Cinema'],pop:87,img:'https://pics.filmaffinity.com/living_in_bondage_breaking_free-971508249-large.jpg',badge:'NIGERIA'},
{t:'King of Boys',y:2018,type:'movie',g:['Crime','Drama','Nigeria','African Cinema'],pop:93,img:'https://fr.web.img6.acsta.net/pictures/19/04/29/14/58/0086198.jpg',badge:'NIGERIA'},
{t:'The Wedding Party',y:2016,type:'movie',g:['Romance','Comedy','Nigeria','African Cinema'],pop:90,img:'https://media.senscritique.com/media/000020919243/0/the_wedding_party.jpg',badge:'NIGERIA'},
{t:'The Figurine: Araromire',y:2010,type:'movie',g:['Mystery','Drama','Nigeria','African Cinema'],pop:83,img:'https://images.justwatch.com/poster/300655798/s718/the-figurine.jpg',badge:'NIGERIA'},
{t:'Hijack 93',y:2024,type:'movie',g:['Thriller','Drama','Nigeria','African Cinema'],pop:89,img:'https://media.senscritique.com/media/000022425172/0/le_detournement.jpg',badge:'NIGERIA'},
{t:'Amina',y:2021,type:'movie',g:['Action','Adventure','Biography','Nigeria','African Cinema'],pop:84,img:'https://cdn.pmnewsnigeria.com/wp-content/uploads/2021/10/EA3A8FE2-05E9-4068-83FC-849EAA20FEB2.jpeg',badge:'NIGERIA'},
{t:'The Man of God',y:2022,type:'movie',g:['Drama','Nigeria','African Cinema'],pop:82,img:'https://cdn.kinocheck.com/i/9ulny1w3az.jpg',badge:'NIGERIA'},
{t:'Swallow',y:2021,type:'movie',g:['Drama','History','Thriller','Nigeria','African Cinema'],pop:83,img:'https://fr.web.img6.acsta.net/pictures/21/09/17/10/08/2854026.jpg',badge:'NIGERIA'},
{t:'Ẹlẹṣin Ọba: The King’s Horseman',y:2022,type:'movie',g:['Drama','Historical','Nigeria','African Cinema'],pop:86,img:'https://de.web.img2.acsta.net/r_1280_720/pictures/22/10/31/14/36/2818809.jpg',badge:'NIGERIA'},
{t:'Sanitation Day',y:2021,type:'movie',g:['Crime','Thriller','Nigeria','African Cinema'],pop:81,img:'https://cdn.businessday.ng/wp-content/uploads/2021/01/sanitation-day.jpg',badge:'NIGERIA'},
{t:'Tòkunbò',y:2024,type:'movie',g:['Action','Crime','Drama','Nigeria','African Cinema'],pop:90,img:'https://www.rexposters.com/images/works/tokunbo.jpg',badge:'NIGERIA'},
{t:'House of Ga’a',y:2024,type:'movie',g:['Action','Historical','Nigeria','African Cinema'],pop:88,img:'https://image.tmdb.org/t/p/original/bDN9VVXYevWz3Bd8g4Weg1NJg9E.jpg',badge:'NIGERIA'},
{t:'Jagun Jagun: The Warrior',y:2023,type:'movie',g:['Action','Historical','Drama','Nigeria','African Cinema'],pop:88,img:'https://image.tmdb.org/t/p/original/4Yon9Qmg3U4onL0OywXAHSkFTUG.jpg',badge:'NIGERIA'},
{t:'Áfàméfùnà: An Nwa Boi Story',y:2023,type:'movie',g:['Drama','Nigeria','African Cinema'],pop:85,img:'https://miro.medium.com/1%2A9dkDNASymuOpgBs_YYntbA.jpeg',badge:'NIGERIA'},
{t:'The Black Book',y:2023,type:'movie',g:['Crime','Thriller','Action','Nigeria','African Cinema'],pop:94,img:'https://image.tmdb.org/t/p/original/xEMkEZhPNQwMfI5FZ4rPcupLKfp.jpg',badge:'NIGERIA'},
{t:'Blood Vessel',y:2023,type:'movie',g:['Drama','Thriller','Survival','Nigeria','African Cinema'],pop:87,img:'https://image.tmdb.org/t/p/original/50BTcsChF9rZ7SVqjBNIo2Em5Mu.jpg',badge:'NIGERIA'},
{t:'Beauty in Black',y:2024,type:'series',g:['Drama','Crime','Series'],pop:97,img:'https://www.essence.com/wp-content/uploads/2025/04/S1-Taylor-2.jpeg',badge:'HOT'},
{t:'Blood Sisters',y:2022,type:'series',g:['Drama','Crime','Thriller','Nigeria','African Cinema','Series'],pop:94,img:'https://www.nollymeter.com/uploads/poster/poster_1747254106.jpg',badge:'NIGERIA'},
{t:'Shanty Town',y:2023,type:'series',g:['Drama','Crime','Thriller','Nigeria','African Cinema','Series'],pop:93,img:'https://artworks.thetvdb.com/banners/v4/series/429156/posters/63cada090149a.jpg',badge:'NIGERIA'},
{t:'To Kill a Monkey',y:2025,type:'series',g:['Drama','Crime','Thriller','Nigeria','African Cinema','Series'],pop:95,img:'https://tobiidowu.com/wp-content/uploads/2025/08/to-kill-a-monkey-review-1.webp',badge:'NEW'},
{t:'Aníkúlápó: The Series',y:2024,type:'series',g:['Drama','Fantasy','Nigeria','African Cinema','Series'],pop:92,img:'https://pics.filmaffinity.com/anikulapo_rise_of_the_spectre-778661580-large.jpg',badge:'NIGERIA'}
];
(function(){window.CINEVAULT_CATALOG=window.CINEVAULT_CATALOG.map(function(m){return Object.assign({},m,{key:encodeURIComponent(m.t)});});})();
