(async function(){
if(window.CINEVAULT_CATALOG_READY)try{await window.CINEVAULT_CATALOG_READY}catch(e){}
const C=window.CINEVAULT_CATALOG||[],p=new URLSearchParams(location.search),requested=p.get('title')||'';
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const catalog=C.find(m=>norm(m.t)===norm(requested))||C.find(m=>norm(m.t).includes(norm(requested))||norm(requested).includes(norm(m.t)));
const corrections={"Hijack 93":{cast:["Nancy Isime","Sharon Ooja","Jemima Osunde","Idia Aisien","Adam Garba","Nnamdi Agbo","Oluwaseyi Akinsola","Allison Emmanuel","Efa Iwara","John Dumelo"],director:"Robert Peters",runtime:"1h 27m",release:"October 4, 2024",country:"Nigeria · English"},"Amina":{runtime:"1h 45m",release:"November 4, 2021",country:"Nigeria · English · Hausa",director:"Izu Ojukwu",cast:["Lucy Ameh","Ali Nuhu","Clarion Chukwura","Chris Gbakann","Ibrahim Mijinyawa"]},"Swallow":{runtime:"2h 08m",release:"October 1, 2021",country:"Nigeria · English",cast:["Eniola ‘Niyola’ Akinbo","Ijeoma Grace Agu","Deyemi Okanlawon","Chioma Chukwuka Akpotha","Eniola Badmus","Mercy Aigbe"],director:"Kunle Afolayan"},"Sanitation Day":{runtime:"1h 44m",release:"December 25, 2020",country:"Nigeria · English",cast:["Blossom Chukwujekwu","Elozanam Ogbolu","Nse Ikpe-Etim","Charles Inojie","Belinda Effah"],director:"Seyi Babatọpe"},"The Man of God":{runtime:"1h 51m",release:"April 16, 2022",country:"Nigeria · English",cast:["Akah Nnani","Osas Ighodaro","Atlanta Bridget Johnson","Dorcas Shola Fapson","Jude Chukwuka","Mawuli Gavor"],director:"Bolanle Austen-Peters"},"Facing El Chapo":{runtime:"1h 31m",release:"August 20, 2026"},"Sniper: The Last Stand":{director:"Danishka Esterhazy",runtime:"1h 39m",release:"January 21, 2025"},"The Last House":{director:"Louis Leterrier",release:"August 7, 2026",runtime:"1h 50m",country:"United States · English",cast:["Greta Lee","Wagner Moura","Riley Chung","Emma Ho","Noah Alexander Sosnowski","Gabriel Barbosa"]}};
const set=(id,v)=>{const e=document.getElementById(id);if(e&&v!=null)e.textContent=v};
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
if(!catalog)return;
let d=(typeof DATA!=='undefined'&&DATA[requested])?DATA[requested]:{};
d=Object.assign({type:catalog.type,genre:(catalog.g||[]).filter(x=>!['Nigeria','African Cinema','African Diaspora','US','UK'].includes(x)).slice(0,4).join(' · ')||'Entertainment',year:String(catalog.y),release:String(catalog.y),runtime:'—',country:(catalog.g||[]).filter(x=>['Nigeria','South Africa','Kenya','Senegal','Mauritania','Africa','US','UK'].includes(x)).join(' · ')||'International',desc:`Discover ${catalog.t}, a ${catalog.y} ${catalog.type==='series'?'series':'film'} selected for the CineVault catalogue. Explore its genre, credits and legitimate viewing destinations.`,cast:[],director:'See official credits',image:catalog.img||''},d,corrections[requested]||{});
set('detailTitle',catalog.t);set('posterTitle',catalog.t.toUpperCase());set('detailGenre',`${d.genre||'ENTERTAINMENT'} · ${d.year||catalog.y}`);set('detailRelease',d.year||catalog.y);set('detailDescription',d.desc);set('metaGenre',d.genre||'Entertainment');set('metaRelease',d.year||catalog.y);set('releaseDate',d.release||catalog.y);set('runtime',d.runtime||'—');set('country',d.country||'International');set('longDescription',d.desc);set('director',d.director||'See official credits');
const cast=document.getElementById('castList');if(cast)cast.innerHTML=d.cast&&d.cast.length?d.cast.map(x=>`<span class="cast-chip">${esc(x)}</span>`).join(''):'<p>Principal cast details are not yet verified in the CineVault catalogue.</p>';
const poster=document.getElementById('detailPoster');if(poster&&d.image){poster.style.backgroundImage=`url("${String(d.image).replace(/"/g,'&quot;')}")`;poster.classList.add('has-detail-image');const strong=poster.querySelector('strong');if(strong)strong.style.opacity='.08'}
const watch=d.watch||catalog.watch||('https://www.justwatch.com/ng/search?q='+encodeURIComponent(catalog.t));
['watchBtn','watchBtn2'].forEach(id=>{const a=document.getElementById(id);if(a){a.href=watch;a.target='_blank';a.rel='noopener noreferrer'}});
const wc=document.getElementById('watchCopy');if(wc)wc.textContent=catalog.watch?'Open the official streaming page for this title.':'Search JustWatch Nigeria for current legal streaming and rental options; availability can change by region.';
let hasAuthorizedDownload=false;try{const r=await fetch('/api/download?title='+encodeURIComponent(catalog.t)+'&check=1',{cache:'no-store'});if(r.ok){const data=await r.json();hasAuthorizedDownload=Boolean(data.available)}}catch(e){console.warn('CineVault download availability check failed',e)}
['downloadBtn','downloadBtn2'].forEach(id=>{const a=document.getElementById(id);if(!a)return;if(hasAuthorizedDownload){a.href='/download.html?title='+encodeURIComponent(catalog.t);a.target='_self';a.rel='noopener';a.removeAttribute('aria-disabled');a.classList.remove('disabled');a.textContent='Download'}else{a.removeAttribute('href');a.setAttribute('aria-disabled','true');a.classList.add('disabled');a.textContent='Download unavailable'}});
const dc=document.getElementById('downloadCopy');if(dc)dc.textContent=hasAuthorizedDownload?'An authorized CineVault file is connected. Your download link is securely prepared when you start the download.':'Direct downloads are enabled only for movies CineVault NG owns, licenses, or is explicitly authorized to distribute.';
const season=document.getElementById('seasonLabel');if(season&&catalog.type==='series')season.textContent=d.season?`Season ${d.season}`:'Series';document.title=`${catalog.t} | CineVault NG`;
})();
