(function(){
const X={
'The Godfather':{genre:'Crime · Drama',release:'March 24, 1972',runtime:'2h 55m',country:'United States · English · Italian',desc:'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son, drawing the family into a struggle of loyalty, power and survival.',cast:['Marlon Brando — Don Vito Corleone','Al Pacino — Michael Corleone','James Caan — Sonny Corleone','Robert Duvall — Tom Hagen','Diane Keaton — Kay Adams'],director:'Francis Ford Coppola',image:'https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',watch:'https://www.justwatch.com/us/movie/the-godfather'},
'Hijack 93':{genre:'Thriller · Drama',release:'October 25, 2024',runtime:'1h 25m',country:'Nigeria · English',desc:'Four young men hijack a commercial flight in a desperate attempt to draw attention to political grievances, turning the journey into a tense confrontation.',cast:['John Dumelo','Idris Elba','Nana Mensah','Sharifah Akinyeele'],director:'Robert Peters',image:'https://media.senscritique.com/media/000022425172/0/le_detournement.jpg',watch:'https://www.netflix.com/ng/title/81676888'},
'Amina':{genre:'Action · Adventure · Biography',release:'November 4, 2021',runtime:'1h 40m',country:'Nigeria · English · Hausa',desc:'Inspired by the legendary Hausa warrior queen, Amina follows a ruler who fights to defend her kingdom and secure her people’s future.',cast:['Lucy Ameh — Amina','Clarion Chukwurah','Maggie Osuome','Ali Nuhu'],director:'Izu Ojukwu',image:'https://cdn.pmnewsnigeria.com/wp-content/uploads/2021/10/EA3A8FE2-05E9-4068-83FC-849EAA20FEB2.jpeg',watch:'https://www.netflix.com/ng/title/81403931'},
'The Man of God':{genre:'Drama',release:'April 16, 2022',runtime:'1h 51m',country:'Nigeria · English',desc:'A young man leaves his father’s strict church life behind, but the past he escaped continues to shape his choices, faith and relationships.',cast:['Akah Nnani — Samuel','Osas Ighodaro — Teju','Atlanta Bridget Johnson','Patrick Doyle'],director:'Bolanle Austen-Peters',image:'https://cdn.kinocheck.com/i/9ulny1w3az.jpg',watch:'https://www.netflix.com/ng/title/81423806'},
'Swallow':{genre:'Drama · History · Thriller',release:'October 1, 2021',runtime:'2h 8m',country:'Nigeria · English · Yoruba',desc:'In 1980s Lagos, a struggling young bank employee faces mounting pressure and is tempted by a dangerous path toward quick money.',cast:['Nolly Thomas — Rose','Eku Edewor — Gold','Deyemi Okanlawon','Enyinna Nwigwe'],director:'Kunle Afolayan',image:'https://fr.web.img6.acsta.net/pictures/21/09/17/10/08/2854026.jpg',watch:'https://www.netflix.com/ng/title/81286691'},
'Ẹlẹṣin Ọba: The King’s Horseman':{genre:'Drama · Historical',release:'November 4, 2022',runtime:'1h 36m',country:'Nigeria · English · Yoruba',desc:'When a Yoruba king dies, his horseman is expected to follow him into death, but colonial intervention disrupts the sacred duty and creates a profound crisis.',cast:['Odunlade Adekola — Elesin Oba','Shaffy Bello — Iyaloja','Deyemi Okanlawon — Simon Pilkings','Jide Kosoko'],director:'Biyi Bandele',image:'https://de.web.img2.acsta.net/r_1280_720/pictures/22/10/31/14/36/2818809.jpg',watch:'https://www.netflix.com/ng/title/81347673'},
'Sanitation Day':{genre:'Crime · Thriller',release:'December 10, 2020',runtime:'1h 37m',country:'Nigeria · English',desc:'During a citywide sanitation exercise, two police officers become entangled in a mystery after discovering a body and uncovering a dangerous cover-up.',cast:['Blossom Chukwujekwu','Enyinna Nwigwe','Nse Ikpe-Etim','Baaj Adebule'],director:'Kenny Orimz',image:'https://cdn.businessday.ng/wp-content/uploads/2021/01/sanitation-day.jpg',watch:'https://www.justwatch.com/us/movie/sanitation-day'}
};
const title=new URLSearchParams(location.search).get('title'),item=X[title];if(!item)return;
const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v||'—'};
set('detailGenre',item.genre+' · '+item.release.slice(-4));set('detailTitle',title);set('detailRelease',item.release.slice(-4));set('metaGenre',item.genre);set('metaRelease',item.release.slice(-4));set('detailDescription',item.desc);set('longDescription',item.desc);set('releaseDate',item.release);set('runtime',item.runtime);set('country',item.country);set('director',item.director);
const poster=document.getElementById('detailPoster');if(poster&&item.image){poster.classList.add('has-image');poster.style.backgroundImage=`url(${item.image})`;const old=poster.querySelector('strong');if(old)old.textContent=title.toUpperCase()}
const list=document.getElementById('castList');if(list)list.innerHTML=item.cast.map(x=>`<div class="cast-item"><b>${x}</b></div>`).join('');
const w1=document.getElementById('watchBtn'),w2=document.getElementById('watchBtn2');[w1,w2].forEach(b=>{if(b){b.href=item.watch;b.target='_blank';b.rel='noopener';b.textContent='Open official / legal option →'}});
})();