const DATA={
'Alpha':{type:'movie',genre:'Action · Spy',release:'July 3, 2026',year:'2026',runtime:'2h 21m',country:'India · Hindi',desc:'After surviving brutal military experiments as a child, an elite assassin is drawn into a dangerous mission that forces her to confront the people who shaped her past.',cast:['Alia Bhatt — Alpha','Sharvari Wagh — key role','Anil Kapoor — senior operative','Bobby Deol — antagonist'],director:'Shiv Rawail',image:'https://de.web.img2.acsta.net/img/ab/48/ab48b27c00127fdc20e2e9222cd36dbd.jpg',provider:'Netflix',search:'Alpha'},
'The Whisper Man':{type:'movie',genre:'Mystery · Thriller',release:'August 28, 2026',year:'2026',runtime:'1h 54m',country:'United States · English',desc:'When his eight-year-old son is abducted, a widowed crime writer turns to his estranged father, a retired detective who once caught a serial killer known as the Whisper Man.',cast:['Robert De Niro — Peter Willis','Adam Scott — Tom Kennedy','Michelle Monaghan — Amanda Beck','Hamish Linklater','Owen Teague','Acston Luca Porto'],director:'James Ashcroft',image:'https://m.media-amazon.com/images/M/MV5BZDdjOTQzMzEtZjYyOC00MWI0LWJlZDItNDBmMDFmODYxZDk1XkEyXkFqcGc%40._V1_.jpg',provider:'Netflix',search:'The Whisper Man'},
'The Secret Woman':{type:'movie',genre:'Drama · Mystery · Thriller',release:'August 28, 2026',year:'2026',runtime:'1h 59m',country:'Denmark · Danish',desc:'Louise Andersen runs a quiet café on a Norwegian island until a stranger tells her she is actually Helene Söderberg, a woman who disappeared three years earlier. She leaves her old life behind to discover what happened and why.',cast:['Natalie Madueño — Louise Andersen / Helene Söderberg','Pål Sverre Hagen — Joachim','Claes Bang — Edmund Söderberg','Stina Ekblad — Caroline','Ingrid Bolsø Berdal — Iben Rask','Lars Simonsen — Aksel Söderberg'],director:'Barbara Topsøe-Rothenborg',provider:'Netflix',search:'The Secret Woman'},
'Anacondas: Trail of Blood':{type:'movie',genre:'Action · Horror · Thriller',release:'February 28, 2009',year:'2009',runtime:'1h 29m',country:'United States · English',desc:'A genetically engineered anaconda regenerates into two giant predators, turning a dangerous expedition into a fight for survival as the team races to stop the creatures.',cast:['Crystal Allen — Amanda','Linden Ashby — Jackson','John Rhys-Davies — Murdoch','Ana Ularu — Heather','Danny Midwinter — Scott','Emil Hostina — Eugene'],director:'Don E. FauntLeRoy',image:'https://m.media-amazon.com/images/S/pv-target-images/f4705001e8d0f143fc2ace8a954c3e9b7973cfa4ea2f3a3da9dda3d49d43fe29.jpg',provider:'Netflix',search:'Anacondas Trail of Blood'},
'Facing El Chapo':{type:'movie',genre:'Action · Crime · Drama',release:'August 20, 2026',year:'2026',runtime:'1h 50m',country:'Mexico · Spanish',desc:'Two Mexican federal officers unexpectedly cross paths with Joaquín “El Chapo” Guzmán and must decide whether to risk everything by turning him in or accept a life-changing offer.',cast:['Alfonso Herrera — Officer Arturo Carmona','Noé Hernández — Officer Héctor Rosales','Héctor Kotsifakis — Joaquín “El Chapo” Guzmán','Juan Pablo Cruz García — El Cholo','Paola Fernández — Isaura Carmona'],director:'Chava Cartas',provider:'Netflix',search:'Facing El Chapo'},
'Colours of Fire':{type:'movie',genre:'Drama · Historical',release:'November 9, 2022',year:'2022',runtime:'2h 15m',country:'France · French',desc:'In 1920s Paris, the daughter of a powerful banker inherits his empire and faces betrayal, corruption and a ruthless struggle for control.',cast:['Léa Drucker','Benoît Poelvoorde','Alice Isaaz','Clovis Cornillac'],director:'Clovis Cornillac',image:'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak%3D/v3/t/assets/p23410678_v_v8_ad.jpg',provider:'Netflix',search:'Colours of Fire'},
'The Last House':{type:'movie',genre:'Thriller · Mystery',release:'2026',year:'2026',runtime:'—',country:'—',desc:'A tense mystery built around a dangerous threat and a desperate struggle to uncover the truth before there is nowhere left to hide.',cast:['Cast details to be verified'],director:'—',image:'https://m.media-amazon.com/images/M/MV5BMjI5YTQ3YmItZjk1ZS00ZDBmLWJhZDMtNThhMDI5ZTRkMTcxXkEyXkFqcGc%40._V1_.jpg',provider:'Netflix',search:'The Last House'},
'Abigail':{type:'movie',genre:'Horror · Thriller',release:'April 19, 2024',year:'2024',runtime:'1h 49m',country:'United States · English',desc:'A group of kidnappers locks themselves inside an isolated mansion with their young hostage, only to discover that the captive is a terrifying vampire with a taste for revenge.',cast:['Alisha Weir — Abigail','Melissa Barrera — Joey','Dan Stevens — Frank','Kathryn Newton — Sammy','Will Catlett — Rickles','Kevin Durand — Peter'],director:'Matt Bettinelli-Olpin & Tyler Gillett',image:'https://static.wixstatic.com/media/699711_e49eb0e95eff44c6bb124491e7ab9184~mv2.png/v1/fill/w_708%2Ch_1000%2Cal_c%2Cq_90%2Cusm_0.66_1.00_0.01/699711_e49eb0e95eff44c6bb124491e7ab9184~mv2.png'},
'Sniper: The Last Stand':{type:'movie',genre:'Action · Military',release:'January 21, 2025',year:'2025',runtime:'1h 39m',country:'United States · English',desc:'An elite sniper leads a small team of soldiers on a dangerous mission to stop an arms dealer from deploying a devastating superweapon.',cast:['Chad Michael Collins — Brandon Beckett','Ryan Robbins','Sharon Taylor','Arnold Vosloo'],director:'Oliver Thompson'},
'2012':{type:'movie',genre:'Action · Disaster · Sci-Fi',release:'November 13, 2009',year:'2009',runtime:'2h 38m',country:'United States · English',desc:'As global disasters threaten civilization, a struggling writer races across a collapsing world to save his family and reach a chance at survival.',cast:['John Cusack — Jackson Curtis','Amanda Peet — Kate Curtis','Chiwetel Ejiofor — Adrian Helmsley','Woody Harrelson — Charlie Frost','Danny Glover — President Wilson'],director:'Roland Emmerich'},
'The Suicide Squad':{type:'movie',genre:'Action · Comedy · Superhero',release:'August 5, 2021',year:'2021',runtime:'2h 12m',country:'United States · English',desc:'A team of imprisoned supervillains is sent on a deadly mission to a remote island where an experiment threatens the world.',cast:['Margot Robbie — Harley Quinn','Idris Elba — Bloodsport','John Cena — Peacemaker','Viola Davis — Amanda Waller','Sylvester Stallone — King Shark'],director:'James Gunn'},
'The Fall Guy':{type:'movie',genre:'Action · Comedy · Romance',release:'May 3, 2024',year:'2024',runtime:'2h 6m',country:'United States · English',desc:'A battle-scarred stuntman returns to a film set to find a missing movie star, uncover a conspiracy and try to win back the love of his life.',cast:['Ryan Gosling — Colt Seavers','Emily Blunt — Jody Moreno','Aaron Taylor-Johnson — Tom Ryder','Hannah Waddingham — Gail Meyer','Winston Duke — Dan Tucker','Stephanie Hsu — Alma Milan'],director:'David Leitch'},
'Beauty in Black':{type:'series',genre:'Drama',release:'August 27, 2026 — Season 3',year:'2024',season:'3',desc:'An ambitious woman rises from a difficult life into the orbit of the powerful Bellarie family, where wealth, betrayal, secrets and a dangerous criminal network collide.',cast:['Taylor Polidore Williams — Kimmie','Crystle Stewart — Mallory','Amber Reign Smith — Rain','Ricco Ross — Horace','Debbi Morgan — Olivia','Richard Lawson — Norman','Steven G. Norfleet — Charles','Julian Horton — Roy','Terrell Carter — Varney'],director:'Tyler Perry',image:'https://www.essence.com/wp-content/uploads/2025/04/S1-Taylor-2.jpeg',provider:'Netflix',search:'Beauty in Black'},
'Mousetrap':{type:'series',genre:'Thriller · Mystery',release:'2026',year:'2026',season:'1',desc:'A suspense-driven mystery in which identity, deception and a relentless pursuit place its characters under mounting pressure.',cast:['Cast details to be verified'],director:'—',image:'https://www.allkpop.com/upload/2026/08/content/141322/1786728168-image.png',provider:'Netflix',search:'Mousetrap'},
'Umthetho':{type:'series',genre:'Crime · Drama',release:'2026',year:'2026',season:'1',desc:'A crime drama focused on power, loyalty and the consequences of choices made on both sides of the law.',cast:['Cast details to be verified'],director:'—',image:'https://fr.web.img6.acsta.net/img/2e/de/2ede9f526864c3d4dac4e1796be5ec7a.jpg',provider:'Netflix',search:'Umthetho'},
'Spooky in Love':{type:'series',genre:'Romance · Supernatural',release:'2026',year:'2026',season:'1',desc:'A romantic supernatural story where love, secrets and the unexplained collide.',cast:['Cast details to be verified'],director:'—',image:'https://resizing.flixster.com/Rj9H15Gj4kOtUcuRi9rxCFcimlw%3D/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvYTg0MmUyMWItNTI3NS00ZjIyLWE0MWItZTk5MzllZjViZmRjLmpwZw%3D%3D',provider:'Netflix',search:'Spooky in Love'},
'Our Sticky Love':{type:'series',genre:'Romance · Comedy',release:'2026',year:'2026',season:'1',desc:'A light romantic comedy about two people whose complicated circumstances turn an unexpected connection into something more.',cast:['Cast details to be verified'],director:'—',image:'https://s359.thaicdn.net/pagebuilder/c9c2ab98-9efe-47c6-be68-f84701fb8a5a.jpg',provider:'Netflix',search:'Our Sticky Love'},
'Death of the Pastor\'s Wife':{type:'series',genre:'True Crime · Documentary',release:'2026',year:'2026',season:'1',desc:'A documentary investigation examines the death of a pastor’s wife and the questions surrounding the case.',cast:['Documentary participants / investigators'],director:'—',image:'https://cdn.bingebase.com/tv_shows/165336/posters/1vY2JjWOKQefWFos9XQ20lqgmtZ.webp',provider:'Netflix',search:"Death of the Pastor's Wife"},
'Four Hands Two Sonatas':{type:'series',genre:'Drama · Music',release:'2026',year:'2026',season:'1',desc:'A music-driven drama exploring relationships, ambition and the pressures surrounding performance.',cast:['Cast details to be verified'],director:'—',provider:'Netflix',search:'Four Hands Two Sonatas'},
'The Early Spring':{type:'series',genre:'Drama · Romance',release:'2026',year:'2026',season:'1',desc:'A relationship-focused drama about love, change and the choices that shape a new chapter in life.',cast:['Cast details to be verified'],director:'—',provider:'Netflix',search:'The Early Spring'},
'Royal House':{type:'series',genre:'Drama',release:'—',year:'—',season:'1',desc:'Power, family and secrets collide behind the doors of a royal household.',cast:['Cast details to be added'],director:'—'},
'After Dark':{type:'series',genre:'Thriller',release:'—',year:'—',season:'2',desc:'When the city sleeps, a new mystery begins.',cast:['Cast details to be added'],director:'—'},
'The Pack':{type:'series',genre:'Fantasy',release:'—',year:'—',season:'1',desc:'An unlikely group discovers that their greatest strength may also be their greatest danger.',cast:['Cast details to be added'],director:'—'},
'New Beginnings':{type:'series',genre:'Romance',release:'—',year:'—',season:'3',desc:'Old feelings return as new beginnings force everyone to choose what they truly want.',cast:['Cast details to be added'],director:'—'}
};
const params=new URLSearchParams(location.search),requested=params.get('title'),item=DATA[requested]||DATA.Alpha,title=requested&&DATA[requested]?requested:'Alpha',$=id=>document.getElementById(id);
if($('detailTitle'))$('detailTitle').textContent=title;
if($('posterTitle'))$('posterTitle').innerHTML=title.toUpperCase().replace(/ /g,'<br>');
if($('detailGenre'))$('detailGenre').textContent=item.genre+(item.type==='movie'&&item.year?` · ${item.year}`:item.type==='series'&&item.season?` · SEASON ${item.season}`:'');
if($('detailDescription'))$('detailDescription').textContent=item.desc;
if($('longDescription'))$('longDescription').textContent=item.desc;
if($('detailRelease'))$('detailRelease').textContent=item.release||item.year||'—';
if($('metaRelease'))$('metaRelease').textContent=item.release||item.year||'—';
if($('releaseDate'))$('releaseDate').textContent=item.release||'—';
if($('runtime'))$('runtime').textContent=item.runtime||'—';
if($('country'))$('country').textContent=item.country||'—';
if($('metaGenre'))$('metaGenre').textContent=item.genre.split(' · ')[0];
if($('seasonCount'))$('seasonCount').textContent=item.season||'—';
if($('director'))$('director').textContent=item.director||'—';
if($('castList'))$('castList').innerHTML=(item.cast||[]).map(c=>`<div class="cast-item">${c}</div>`).join('');
if($('detailPoster')){if(item.image){const img=document.createElement('img');img.src=item.image;img.alt=`${title} poster`;img.loading='eager';img.referrerPolicy='no-referrer';$('detailPoster').insertBefore(img,$('detailPoster').firstChild);$('detailPoster').classList.add('has-image');}}
document.title=`${title} | CineVault NG`;
if(item.type==='series'&&item.season){if($('metaSeason'))$('metaSeason').textContent=item.season;if($('seasonLabel'))$('seasonLabel').textContent=`Season ${item.season}`;}
const officialUrl=item.provider==='Netflix'&&item.search?`https://www.netflix.com/ng/search?q=${encodeURIComponent(item.search)}`:'#';
['watchBtn','watchBtn2'].forEach(id=>{const btn=$(id);if(!btn)return;if(officialUrl!=='#'){btn.href=officialUrl;btn.target='_blank';btn.rel='noopener noreferrer';btn.textContent=`Find on ${item.provider}`;}else{btn.href='#';btn.addEventListener('click',e=>{e.preventDefault();alert('The official viewing link has not been added yet.');});}});
['downloadBtn','downloadBtn2'].forEach(id=>{const btn=$(id);if(!btn)return;btn.href='#';btn.addEventListener('click',e=>{e.preventDefault();alert('Direct downloads are available only for titles CineVault NG owns, licenses, or is explicitly authorized to distribute.');});});
