const DATA={
'Alpha':{type:'movie',genre:'Action · Spy',release:'July 3, 2026',year:'2026',runtime:'2h 21m',country:'India · Hindi',desc:'After surviving brutal military experiments as a child, an elite assassin is drawn into a dangerous mission that forces her to confront the people who shaped her past.',cast:['Alia Bhatt — Alpha','Sharvari Wagh — key role','Anil Kapoor — senior operative','Bobby Deol — antagonist'],director:'Shiv Rawail',image:'https://de.web.img2.acsta.net/img/ab/48/ab48b27c00127fdc20e2e9222cd36dbd.jpg',provider:'Netflix',search:'Alpha'},
'The Whisper Man':{type:'movie',genre:'Mystery · Thriller',release:'August 28, 2026',year:'2026',runtime:'1h 54m',country:'United States · English',desc:'When his eight-year-old son is abducted, a widowed crime writer turns to his estranged father, a retired detective who once caught a serial killer known as the Whisper Man.',cast:['Robert De Niro — Peter Willis','Adam Scott — Tom Kennedy','Michelle Monaghan — Amanda Beck','Hamish Linklater','Owen Teague','Acston Luca Porto'],director:'James Ashcroft',image:'https://m.media-amazon.com/images/M/MV5BZDdjOTQzMzEtZjYyOC00MWI0LWJlZDItNDBmMDFmODYxZDk1XkEyXkFqcGc%40._V1_.jpg',provider:'Netflix',search:'The Whisper Man'},
'The Secret Woman':{type:'movie',genre:'Drama · Mystery · Thriller',release:'August 28, 2026',year:'2026',runtime:'1h 59m',country:'Denmark · Danish',desc:'Louise Andersen runs a quiet café on a Norwegian island until a stranger tells her she is actually Helene Söderberg, a woman who disappeared three years earlier. She leaves her old life behind to discover what happened and why.',cast:['Natalie Madueño — Louise Andersen / Helene Söderberg','Pål Sverre Hagen — Joachim','Claes Bang — Edmund Söderberg','Stina Ekblad — Caroline','Ingrid Bolsø Berdal — Iben Rask','Lars Simonsen — Aksel Söderberg'],director:'Barbara Topsøe-Rothenborg',image:'https://images.ctfassets.net/4cd45et68cgf/3mbqqX0cP4YdbTnOVLUt45/9842421100e45de47e3fb543eddb6aac/TheSecretWoman__23A5805_LasseBakMejlvang_Netflix.jpg?w=1000',provider:'Netflix',search:'The Secret Woman'},
'Anacondas: Trail of Blood':{type:'movie',genre:'Action · Horror · Thriller',release:'February 28, 2009',year:'2009',runtime:'1h 29m',country:'United States · English',desc:'A genetically engineered anaconda regenerates into two giant predators, turning a dangerous expedition into a fight for survival as the team races to stop the creatures.',cast:['Crystal Allen — Amanda','Linden Ashby — Jackson','John Rhys-Davies — Murdoch','Ana Ularu — Heather','Danny Midwinter — Scott','Emil Hostina — Eugene'],director:'Don E. FauntLeRoy',image:'https://m.media-amazon.com/images/S/pv-target-images/f4705001e8d0f143fc2ace8a954c3e9b7973cfa4ea2f3a3da9dda3d49d43fe29.jpg',provider:'Netflix',search:'Anacondas Trail of Blood'},
'Facing El Chapo':{type:'movie',genre:'Action · Crime · Drama',release:'August 20, 2026',year:'2026',runtime:'1h 31m',country:'Mexico · Spanish',desc:'Two Mexican officers must survive the final hours of their shift after crossing a ruthless cartel boss in this crime drama inspired by the operation that led to Joaquín “El Chapo” Guzmán’s recapture.',cast:['Alfonso Herrera — Officer Arturo Carmona','Noé Hernández — Officer Héctor Rosales','Héctor Kotsifakis — Joaquín “El Chapo” Guzmán','Juan Pablo Cruz García — El Cholo','Paola Fernández — Isaura Carmona'],director:'Chava Cartas',image:'https://image.tmdb.org/t/p/original/etFPzmqXZlHDderOCgg3YjQswT1.jpg',provider:'Netflix',search:'Facing El Chapo'},
'Colours of Fire':{type:'movie',genre:'Drama · Historical',release:'November 9, 2022',year:'2022',runtime:'2h 15m',country:'France · French',desc:'In 1920s Paris, the daughter of a powerful banker inherits his empire and faces betrayal, corruption and a ruthless struggle for control.',cast:['Léa Drucker','Benoît Poelvoorde','Alice Isaaz','Clovis Cornillac'],director:'Clovis Cornillac',image:'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak%3D/v3/t/assets/p23410678_v_v8_ad.jpg',provider:'Netflix',search:'Colours of Fire'},
'The Last House':{type:'movie',genre:'Sci-Fi · Thriller',release:'August 7, 2026',year:'2026',runtime:'1h 50m',country:'United States · English',desc:'A family is mysteriously sealed inside their home and must survive dwindling resources while an ominous force outside threatens to break through.',cast:['Greta Lee','Wagner Moura','Riley Chung','Emma Ho','Noah Alexander Sosnowski','Gabriel Barbosa'],director:'Louis Leterrier',image:'https://v1.fdbimg.pl/crop?height=1350&noprofile=true&quality=80&sign=FpT5yReI0sZNpxvGrE5VsGB9o-CBKZdmjnlqer162RA&stripmeta=true&type=webp&url=https%3A%2F%2Fi11.fdbimg.pl%2Fi%2Fv%2Fp%2Fx%2Fvpxi5c6qcbta5e27zzgq6lpawyw2&width=931',provider:'Netflix',search:'The Last House'},
'Abigail':{type:'movie',genre:'Horror · Thriller',release:'April 19, 2024',year:'2024',runtime:'1h 49m',country:'United States · English',desc:'A group of kidnappers locks themselves inside an isolated mansion with their young hostage, only to discover that the captive is a terrifying vampire with a taste for revenge.',cast:['Alisha Weir — Abigail','Melissa Barrera — Joey','Dan Stevens — Frank','Kathryn Newton — Sammy','Will Catlett — Rickles','Kevin Durand — Peter'],director:'Matt Bettinelli-Olpin & Tyler Gillett',image:'https://static.wixstatic.com/media/699711_e49eb0e95eff44c6bb124491e7ab9184~mv2.png/v1/fill/w_708%2Ch_1000%2Cal_c%2Cq_90%2Cusm_0.66_1.00_0.01/699711_e49eb0e95eff44c6bb124491e7ab9184~mv2.png',provider:'Netflix',search:'Abigail'},
'Sniper: The Last Stand':{type:'movie',genre:'Action · Military',release:'January 21, 2025',year:'2025',runtime:'1h 39m',country:'United States · English',desc:'An elite sniper leads a small team of soldiers on a dangerous mission to stop an arms dealer from deploying a devastating superweapon.',cast:['Chad Michael Collins — Brandon Beckett','Ryan Robbins','Sharon Taylor','Arnold Vosloo'],director:'Danishka Esterhazy',image:'https://screenanarchy.com/assets/2025/01/DP_9533385_SNIPERTHELASTSTAND_2000x3000LSR_HEKeyArt.jpg',provider:'Netflix',search:'Sniper The Last Stand'},
'2012':{type:'movie',genre:'Action · Disaster · Sci-Fi',release:'November 13, 2009',year:'2009',runtime:'2h 38m',country:'United States · English',desc:'As global disasters threaten civilization, a struggling writer races across a collapsing world to save his family and reach a chance at survival.',cast:['John Cusack — Jackson Curtis','Amanda Peet — Kate Curtis','Chiwetel Ejiofor — Adrian Helmsley','Woody Harrelson — Charlie Frost','Danny Glover — President Wilson'],director:'Roland Emmerich'},
'The Suicide Squad':{type:'movie',genre:'Action · Comedy · Superhero',release:'August 5, 2021',year:'2021',runtime:'2h 12m',country:'United States · English',desc:'A team of imprisoned supervillains is sent on a deadly mission to a remote island where an experiment threatens the world.',cast:['Margot Robbie — Harley Quinn','Idris Elba — Bloodsport','John Cena — Peacemaker','Viola Davis — Amanda Waller','Sylvester Stallone — King Shark'],director:'James Gunn'},
'The Fall Guy':{type:'movie',genre:'Action · Comedy · Romance',release:'May 3, 2024',year:'2024',runtime:'2h 6m',country:'United States · English',desc:'A battle-scarred stuntman returns to a film set to find a missing movie star, uncover a conspiracy and try to win back the love of his life.',cast:['Ryan Gosling — Colt Seavers','Emily Blunt — Jody Moreno','Aaron Taylor-Johnson — Tom Ryder','Hannah Waddingham — Gail Meyer','Winston Duke — Dan Tucker','Stephanie Hsu — Alma Milan'],director:'David Leitch'},
'The Heat':{type:'movie',genre:'Comedy · Action',release:'June 28, 2013',year:'2013',runtime:'1h 57m',country:'United States · English',desc:'A tightly wound FBI agent and a foul-mouthed Boston detective are forced to work together to bring down a drug lord.',cast:['Sandra Bullock — Sarah Ashburn','Melissa McCarthy — Shannon Mullins','Demián Bichir — Hale','Marlon Wayans — Levy'],director:'Paul Feig'},
'The Black Book':{type:'movie',genre:'Crime · Thriller · Action',release:'September 22, 2023',year:'2023',runtime:'2h 4m',country:'Nigeria · English · Nigerian Pidgin',desc:'After his son is framed for a kidnapping and killed, a bereaved deacon with a violent past takes justice into his own hands and fights a corrupt police gang to expose the truth.',cast:['Richard Mofe-Damijo — Paul Edima','Ade Laoye — Vic Kalu','Sam Dede — Angel','Ireti Doyle — Commissioner','Shaffy Bello — Big Daddy','Alex Usifo — General Issa'],director:'Editi Effiong',image:'https://image.tmdb.org/t/p/original/xEMkEZhPNQwMfI5FZ4rPcupLKfp.jpg',provider:'Netflix',search:'The Black Book'},
'Blood Vessel':{type:'movie',genre:'Drama · Thriller · Survival',release:'December 8, 2023',year:'2023',runtime:'1h 58m',country:'Nigeria · English · Ijaw',desc:'Six people fleeing a town devastated by oil pollution hide aboard a mysterious ship, only to discover that the vessel carries dangers of its own.',cast:['Adaobi Dibor','David Ezekiel','Sylvester Ekanem','Obinna Christian Okenwa','Alex Cyr Budin','Levi Chikere','Ekene Achufusi'],director:'Moses Inwang',image:'https://image.tmdb.org/t/p/original/50BTcsChF9rZ7SVqjBNIo2Em5Mu.jpg',provider:'Netflix',search:'Blood Vessel'},
'Tòkunbò':{type:'movie',genre:'Action · Crime · Drama',release:'August 23, 2024',year:'2024',runtime:'1h 52m',country:'Nigeria · English · Yoruba · Nigerian Pidgin · Igbo',desc:'An ex-car smuggler is given three hours to deliver a government official’s daughter to her captor, or his family will suffer the consequences.',cast:['Gideon Okeke — Tòkunbò','Chidi Mokeme — Gaza','Funlola Aofiyebi-Raimi — Folashade','Adunni Ade — Iya Mulika','Darasimi Nadi — Nike','Norbert Young — ASP Salim','Majid Michel — Raymond/Agba'],director:'Ramsey Nouah',provider:'Netflix',search:'Tòkunbò'},
'House of Ga\'a':{type:'movie',genre:'Action · Historical',release:'July 26, 2024',year:'2024',runtime:'2h',country:'Nigeria · English · Yoruba',desc:'A powerful Yoruba military leader rises through ambition and intrigue, but his hunger for influence creates enemies and threatens the kingdom around him.',cast:['Femi Branch','Femi Adebayo','Funke Akindele','Lateef Adedimeji','Mike Afolarin','Toyin Abraham','Ibrahim Chatta'],director:'Bolanle Austen-Peters',image:'https://image.tmdb.org/t/p/original/bDN9VVXYevWz3Bd8g4Weg1NJg9E.jpg',provider:'Netflix',search:"House of Ga'a"},
'Jagun Jagun: The Warrior':{type:'movie',genre:'Action · Drama · Historical',release:'August 10, 2023',year:'2023',runtime:'2h 14m',country:'Nigeria · Yoruba',desc:'A young man determined to become a warrior joins a military academy, where ambition, loyalty, romance and a powerful commander collide.',cast:['Femi Adebayo','Lateef Adedimeji','Odunlade Adekola','Ibrahim Yekini','Bukunmi Oluwashina','Fathia Balogun','Adebayo Salami'],director:'Adebayo Tijani & Tope Adebayo',image:'https://image.tmdb.org/t/p/original/4Yon9Qmg3U4onL0OywXAHSkFTUG.jpg',provider:'Netflix',search:'Jagun Jagun'},
'Áfàméfùnà: An Nwa Boi Story':{type:'movie',genre:'Drama · Igbo Culture',release:'December 1, 2023',year:'2023',runtime:'1h 53m',country:'Nigeria · Igbo',desc:'A young Igbo apprentice faces loyalty, friendship, family expectations and the pressures of the traditional Nwa Boi apprenticeship system.',cast:['Stan Nze','Kanayo O. Kanayo','Alexx Ekubo','Segun Arinze','Atlanta Bridget Johnson'],director:'Kayode Kasum',provider:'Netflix',search:'Afamefuna'},
'Spider-Man: Into the Spider-Verse':{type:'movie',genre:'Animation · Action · Adventure',release:'December 14, 2018',year:'2018',runtime:'1h 57m',country:'United States · English',desc:'Teenager Miles Morales becomes Spider-Man and joins heroes from parallel dimensions to stop a threat that could destroy their worlds.',cast:['Shameik Moore — Miles Morales','Jake Johnson — Peter B. Parker','Hailee Steinfeld — Gwen Stacy','Mahershala Ali — Aaron Davis','Brian Tyree Henry — Jefferson Davis','Nicolas Cage — Spider-Man Noir'],director:'Bob Persichetti, Peter Ramsey & Rodney Rothman',image:'https://image.tmdb.org/t/p/original/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg'},
'Beauty in Black':{type:'series',genre:'Drama · Crime',release:'August 27, 2026 — Season 3',year:'2024',season:'3',desc:'Kimmie rises from a difficult life into the orbit of the powerful Bellarie family, where wealth, betrayal, secrets and a dangerous criminal network collide.',cast:['Taylor Polidore Williams — Kimmie','Crystle Stewart — Mallory','Amber Reign Smith — Rain','Ricco Ross — Horace','Debbi Morgan — Olivia','Richard Lawson — Norman'],director:'Tyler Perry',image:'https://www.essence.com/wp-content/uploads/2025/04/S1-Taylor-2.jpeg',provider:'Netflix',search:'Beauty in Black'},
'Blood Sisters':{type:'series',genre:'Drama · Crime · Thriller',release:'May 5, 2022',year:'2022',season:'1',desc:'Bound by a dangerous secret, best friends Sarah and Kemi go on the run after a wealthy groom disappears during his engagement party.',cast:['Ini Dima-Okojie — Sarah','Nancy Isime — Kemi','Kate Henshaw-Nuttal','Genoveva Umeh','Uche Jombo','Daniel Etim Effiong','Gabriel Afolayan'],director:'Temidayo Makanjuola',provider:'Netflix',search:'Blood Sisters'},
'Shanty Town':{type:'series',genre:'Drama · Crime · Thriller',release:'January 20, 2023',year:'2023',season:'1',desc:'A group of courtesans tries to escape a notorious Lagos kingpin, but political corruption and blood ties make freedom almost impossible.',cast:['Ini Edo','Chidi Mokeme','Richard Mofe-Damijo','Sola Sobowale','Nse Ikpe-Etim','Zubby Michael','Shaffy Bello','Nancy Isime'],director:'Xavier Ighorodje',provider:'Netflix',search:'Shanty Town'},
'To Kill a Monkey':{type:'series',genre:'Drama · Crime · Thriller',release:'2025',year:'2025',season:'1',desc:'Enticed into the lucrative world of cybercrime, a struggling father faces a moral minefield where every choice leads him to greater compromises.',cast:['William Benson','Bucci Franklin','Bimbo Akintola','Stella Damasus','Chidi Mokeme','Iretiola Doyle'],director:'Kemi Adetiba',provider:'Netflix',search:'To Kill a Monkey'},
'Aníkúlápó: The Series':{type:'series',genre:'Drama · Fantasy · Period',release:'2026',year:'2026',season:'1',desc:'In a race against time to avoid a dismal fate, traveler Saro returns to Ojumo with orders to complete a nearly impossible task.',cast:['Owobo Ogunde','Sola Sobowale','Taiwo Hassan'],director:'Kunle Afolayan',provider:'Netflix',search:'Aníkúlápó: The Series'}
};

const params=new URLSearchParams(location.search),requested=params.get('title'),item=DATA[requested]||DATA.Alpha,title=requested&&DATA[requested]?requested:'Alpha',$=id=>document.getElementById(id);
if($('detailTitle'))$('detailTitle').textContent=title;
if($('posterTitle'))$('posterTitle').innerHTML=title.toUpperCase().replace(/ /g,'<br>');
if($('detailGenre'))$('detailGenre').textContent=item.genre+(item.type==='movie'&&item.year?` · ${item.year}`:item.type==='series'&&item.season?` · SEASON ${item.season}`:'');
if($('detailDescription'))$('detailDescription').textContent=item.desc;
if($('longDescription'))$('longDescription').textContent=item.desc;
if($('detailRelease'))$('detailRelease').textContent=item.release||item.year||'—';
if($('metaRelease'))$('metaRelease').textContent=item.release||item.year||'—';
if($('releaseDate'))$('releaseDate').textContent=item.release||'—';
if($('runtime'))$('runtime').textContent=item.runtime||'—';
if($('country'))$('country').textContent=item.country||'—';
if($('metaGenre'))$('metaGenre').textContent=(item.genre||'').split(' · ')[0];
if($('seasonCount'))$('seasonCount').textContent=item.season||'—';
if($('director'))$('director').textContent=item.director||'—';
if($('castList'))$('castList').innerHTML=(item.cast||[]).map(c=>`<div class="cast-item">${c}</div>`).join('');
if($('detailPoster')){
  if(item.image){
    const img=document.createElement('img');img.src=item.image;img.alt=`${title} poster`;img.loading='eager';img.referrerPolicy='no-referrer';
    img.onerror=()=>{$('detailPoster').classList.remove('has-image');img.remove();};
    $('detailPoster').insertBefore(img,$('detailPoster').firstChild);$('detailPoster').classList.add('has-image');
  }
}
document.title=`${title} | CineVault NG`;
if(item.type==='series'&&item.season){if($('metaSeason'))$('metaSeason').textContent=item.season;if($('seasonLabel'))$('seasonLabel').textContent=`Season ${item.season}`;}

const officialUrl=item.provider==='Netflix'&&item.search?`https://www.netflix.com/ng/search?q=${encodeURIComponent(item.search)}`:'#';
['watchBtn','watchBtn2'].forEach(id=>{const btn=$(id);if(!btn)return;if(officialUrl!=='#'){btn.href=officialUrl;btn.target='_blank';btn.rel='noopener noreferrer';btn.textContent=`Find on ${item.provider}`;}else{btn.href='#';btn.textContent='Official link not added';btn.addEventListener('click',e=>e.preventDefault());}});

const authorizedDownload=item.downloadUrl||null;
['downloadBtn','downloadBtn2'].forEach(id=>{const btn=$(id);if(!btn)return;if(authorizedDownload){btn.href=authorizedDownload;btn.target='_blank';btn.rel='noopener';btn.setAttribute('download','');btn.textContent='Download';}else{btn.href='#';btn.textContent='Download unavailable';btn.setAttribute('aria-disabled','true');btn.addEventListener('click',e=>{e.preventDefault();alert('Direct downloads are enabled only for movies CineVault NG owns, licenses, or is explicitly authorized to distribute. Official streaming downloads must be made inside the streaming service.');});}});
if($('downloadCopy'))$('downloadCopy').textContent=authorizedDownload?'Authorized download available for this title.':'Direct downloads are enabled only for movies CineVault NG owns, licenses, or is explicitly authorized to distribute. For third-party titles, use the official viewing service.';
if($('watchCopy'))$('watchCopy').textContent=officialUrl!=='#'?`This title is listed for legal viewing through ${item.provider}. Availability can vary by country.`:'No official viewing destination has been added yet.';
