(function(){
const X={
'Pulp Fiction':{y:'1994',genre:'Crime · Drama',release:'October 14, 1994',runtime:'2h 34m',country:'United States · English',desc:'Two hitmen, a boxer, a gangster and his wife, and a pair of robbers become caught in a series of sharply connected stories of crime, chance and redemption.',cast:['John Travolta — Vincent Vega','Samuel L. Jackson — Jules Winnfield','Uma Thurman — Mia Wallace','Bruce Willis — Butch Coolidge','Ving Rhames — Marsellus Wallace'],director:'Quentin Tarantino',image:'https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',watch:'https://www.justwatch.com/us/movie/pulp-fiction'},
'Spirited Away':{y:'2001',genre:'Animation · Fantasy · Adventure',release:'July 20, 2001',runtime:'2h 5m',country:'Japan · Japanese',desc:'A young girl enters a mysterious spirit world after her parents are transformed, and she must find courage and resourcefulness to free them and return home.',cast:['Rumi Hiiragi — Chihiro','Miyu Irino — Haku','Mari Natsuki — Yubaba','Bunta Sugawara — Kamaji'],director:'Hayao Miyazaki',image:'https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',watch:'https://www.justwatch.com/us/movie/spirited-away'},
'Mad Max: Fury Road':{y:'2015',genre:'Action · Adventure · Sci-Fi',release:'May 15, 2015',runtime:'2h',country:'Australia · United States · English',desc:'In a devastated wasteland, Max joins Furiosa and a group of fleeing women in a relentless pursuit across the desert against a brutal warlord.',cast:['Tom Hardy — Max Rockatansky','Charlize Theron — Imperator Furiosa','Nicholas Hoult — Nux','Hugh Keays-Byrne — Immortan Joe'],director:'George Miller',image:'https://image.tmdb.org/t/p/original/hA2ple9q4qnwxp3hKVNhroipsir.jpg',watch:'https://www.justwatch.com/us/movie/mad-max-fury-road'},
'Get Out':{y:'2017',genre:'Horror · Mystery · Thriller',release:'February 24, 2017',runtime:'1h 44m',country:'United States · English',desc:'A young Black man visits his white girlfriend’s family estate and discovers a disturbing secret beneath the family’s polite hospitality.',cast:['Daniel Kaluuya — Chris Washington','Allison Williams — Rose Armitage','Bradley Whitford — Dean Armitage','Catherine Keener — Missy Armitage'],director:'Jordan Peele',image:'https://image.tmdb.org/t/p/original/tFXcEccSQMf3lfhf4yHf9f1b6mH.jpg',watch:'https://www.justwatch.com/us/movie/get-out'},
'Top Gun: Maverick':{y:'2022',genre:'Action · Drama',release:'May 27, 2022',runtime:'2h 11m',country:'United States · English',desc:'After decades as one of the Navy’s finest aviators, Pete “Maverick” Mitchell returns to train a new generation of elite pilots for an extraordinarily dangerous mission.',cast:['Tom Cruise — Pete “Maverick” Mitchell','Miles Teller — Bradley “Rooster” Bradshaw','Jennifer Connelly — Penny Benjamin','Jon Hamm — Beau “Cyclone” Simpson','Glen Powell — Jake “Hangman” Seresin'],director:'Joseph Kosinski',image:'https://image.tmdb.org/t/p/original/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',watch:'https://www.justwatch.com/us/movie/top-gun-maverick'},
'Black Panther':{y:'2018',genre:'Action · Adventure · Superhero',release:'February 16, 2018',runtime:'2h 14m',country:'United States · English · Xhosa',desc:'After his father’s death, T’Challa returns to Wakanda to take the throne, only to face a challenger whose arrival threatens the future of the isolated kingdom.',cast:['Chadwick Boseman — T’Challa / Black Panther','Michael B. Jordan — Erik Killmonger','Lupita Nyong’o — Nakia','Danai Gurira — Okoye','Danai Gurira — Okoye'],director:'Ryan Coogler',image:'https://image.tmdb.org/t/p/original/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',watch:'https://www.justwatch.com/us/movie/black-panther'},
'Avengers: Endgame':{y:'2019',genre:'Action · Adventure · Superhero',release:'April 26, 2019',runtime:'3h 1m',country:'United States · English',desc:'After a devastating defeat, the surviving Avengers make one final attempt to reverse the catastrophe and restore what was lost.',cast:['Robert Downey Jr. — Tony Stark / Iron Man','Chris Evans — Steve Rogers / Captain America','Mark Ruffalo — Bruce Banner / Hulk','Chris Hemsworth — Thor','Scarlett Johansson — Natasha Romanoff'],director:'Anthony Russo & Joe Russo',image:'https://image.tmdb.org/t/p/original/or06FN3Dka5tukK1e9sl16pB3iy.jpg',watch:'https://www.justwatch.com/us/movie/avengers-endgame'},
'The Shawshank Redemption':{y:'1994',genre:'Drama',release:'September 23, 1994',runtime:'2h 22m',country:'United States · English',desc:'A banker convicted of a double murder forms an enduring friendship inside prison while quietly holding on to hope and planning for a different future.',cast:['Tim Robbins — Andy Dufresne','Morgan Freeman — Ellis “Red” Redding','Bob Gunton — Warden Norton','William Sadler — Heywood'],director:'Frank Darabont',image:'https://image.tmdb.org/t/p/original/lyQBXzOQTgK6J6H8m4u8YfQfF7Q.jpg',watch:'https://www.justwatch.com/us/movie/the-shawshank-redemption'},
'Gladiator':{y:'2000',genre:'Action · Drama · History',release:'May 5, 2000',runtime:'2h 35m',country:'United States · United Kingdom · English',desc:'A betrayed Roman general is forced into slavery and the arena, where he rises as a gladiator and seeks justice against the emperor who destroyed his family.',cast:['Russell Crowe — Maximus','Joaquin Phoenix — Commodus','Connie Nielsen — Lucilla','Oliver Reed — Proximo'],director:'Ridley Scott',image:'https://image.tmdb.org/t/p/original/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',watch:'https://www.justwatch.com/us/movie/gladiator'},
'The Lion King':{y:'1994',genre:'Animation · Family · Adventure',release:'June 24, 1994',runtime:'1h 28m',country:'United States · English',desc:'A young lion prince must find his place in the circle of life after tragedy drives him away from his kingdom and his responsibilities.',cast:['Matthew Broderick — Simba','Jeremy Irons — Scar','James Earl Jones — Mufasa','Moira Kelly — Nala','Nathan Lane — Timon'],director:'Roger Allers & Rob Minkoff',image:'https://image.tmdb.org/t/p/original/2e853FDVSIso600tD7t8K0d5D6T.jpg',watch:'https://www.justwatch.com/us/movie/the-lion-king-1994'},
'Jurassic Park':{y:'1993',genre:'Adventure · Sci-Fi · Thriller',release:'June 11, 1993',runtime:'2h 7m',country:'United States · English',desc:'A group of scientists and visitors are invited to an island theme park where genetically engineered dinosaurs escape their enclosures with terrifying consequences.',cast:['Sam Neill — Alan Grant','Laura Dern — Ellie Sattler','Jeff Goldblum — Ian Malcolm','Richard Attenborough — John Hammond'],director:'Steven Spielberg',image:'https://image.tmdb.org/t/p/original/fjTU1Bgh3KJu4GQj7Gf7G5m8Y9d.jpg',watch:'https://www.justwatch.com/us/movie/jurassic-park'},
'Coco':{y:'2017',genre:'Animation · Family · Fantasy',release:'November 22, 2017',runtime:'1h 45m',country:'United States · English · Spanish',desc:'A young aspiring musician enters the Land of the Dead and uncovers generations of family history while trying to understand his place in the world.',cast:['Anthony Gonzalez — Miguel','Gael García Bernal — Héctor','Benjamin Bratt — Ernesto de la Cruz','Alanna Ubach — Mamá Imelda'],director:'Lee Unkrich & Adrian Molina',image:'https://image.tmdb.org/t/p/original/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',watch:'https://www.justwatch.com/us/movie/coco-2017'}
};
const title=new URLSearchParams(location.search).get('title');const item=X[title];if(!item)return;
const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v||'—'};
set('detailGenre',item.genre+' · '+item.y);set('detailTitle',title);set('detailRelease',item.y);set('metaGenre',item.genre);set('metaRelease',item.y);set('detailDescription',item.desc);set('longDescription',item.desc);set('releaseDate',item.release);set('runtime',item.runtime);set('country',item.country);set('director',item.director);
const poster=document.getElementById('detailPoster');if(poster&&item.image){poster.classList.add('has-image');poster.style.backgroundImage=`url(${item.image})`}
const list=document.getElementById('castList');if(list)list.innerHTML=item.cast.map(x=>`<div class="cast-item"><b>${x}</b></div>`).join('');
const w1=document.getElementById('watchBtn'),w2=document.getElementById('watchBtn2');[w1,w2].forEach(b=>{if(b){b.href=item.watch;b.target='_blank';b.rel='noopener';b.textContent='Open official / legal option →'}});
})();