(function(){
const fallbackCache=new Map();
const normalize=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function svgData(title,year,badge){const key=normalize(title)+'|'+year;if(fallbackCache.has(key))return fallbackCache.get(key);const words=String(title||'CineVault').split(/\s+/).filter(Boolean),initials=(words.slice(0,3).map(w=>w[0]).join('')||'CV').toUpperCase(),safeTitle=esc(title||'CineVault'),safeYear=esc(year||''),safeBadge=esc(badge||'CINEVAULT');const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#111821"/><stop offset="1" stop-color="#3a1f27"/></linearGradient><radialGradient id="r" cx="75%" cy="15%" r="70%"><stop offset="0" stop-color="#b84b57" stop-opacity=".8"/><stop offset="1" stop-color="#b84b57" stop-opacity="0"/></radialGradient></defs><rect width="600" height="900" fill="url(#g)"/><rect width="600" height="900" fill="url(#r)"/><circle cx="80" cy="120" r="120" fill="#b84b57" opacity=".14"/><circle cx="560" cy="720" r="190" fill="#7a3944" opacity=".16"/><path d="M0 700 L600 360 L600 900 L0 900Z" fill="#07090d" opacity=".62"/><text x="42" y="82" fill="#b5bcc8" font-family="Arial,sans-serif" font-size="24" font-weight="700" letter-spacing="4">${safeBadge}</text><text x="42" y="520" fill="#eef1f5" font-family="Arial,sans-serif" font-size="96" font-weight="800">${esc(initials)}</text><text x="42" y="610" fill="#eef1f5" font-family="Arial,sans-serif" font-size="34" font-weight="700">${safeTitle.length>24?safeTitle.slice(0,24)+'…':safeTitle}</text><text x="42" y="660" fill="#9ea7b3" font-family="Arial,sans-serif" font-size="24">${safeYear}</text><text x="42" y="840" fill="#b84b57" font-family="Arial,sans-serif" font-size="20" font-weight="700" letter-spacing="3">CINEVAULT NG</text></svg>`;const uri='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg);fallbackCache.set(key,uri);return uri}
function catalog(){return Array.isArray(window.CINEVAULT_CATALOG)?window.CINEVAULT_CATALOG:[]}
function lookup(title){const n=normalize(title);return catalog().find(m=>normalize(m.t)===n)||catalog().find(m=>normalize(m.t).includes(n)||n.includes(normalize(m.t)))}
function posterFor(item,title){return item?.img||window.CINEVAULT_POSTERS?.[item?.t]||window.CINEVAULT_POSTERS?.[title]||''}
function makeFallback(card){const poster=card?.querySelector('.poster');if(!poster||poster.querySelector('img.generated-poster'))return;const title=card.dataset.title||card.querySelector('h3')?.textContent||'CineVault',item=lookup(title),img=document.createElement('img');img.alt=title+' poster';img.loading='lazy';img.dataset.fallbackApplied='true';img.className='generated-poster';img.src=svgData(item?.t||title,item?.y||'',item?.badge||'CINEVAULT');poster.classList.add('image-poster');poster.prepend(img)}
function applyGenerated(img,card){if(img.dataset.fallbackApplied)return;const title=card?.dataset.title||card?.querySelector('h3')?.textContent||img?.alt?.replace(/\s+poster.*$/i,'')||'CineVault',item=lookup(title);img.dataset.fallbackApplied='true';img.src=svgData(item?.t||title,item?.y||'',item?.badge||'CINEVAULT');img.classList.add('generated-poster')}
function proxy(src){return src&&/^https?:\/\//i.test(src)?'https://wsrv.nl/?url='+encodeURIComponent(src):src}
function bind(img){if(img.dataset.posterBound)return;img.dataset.posterBound='true';img.referrerPolicy='no-referrer';img.decoding='async';const original=img.src;img.dataset.originalSrc=original;if(/^https?:\/\//i.test(original)&&!/wsrv\.nl\//.test(original)){img.dataset.proxyTried='true';img.src=proxy(original)}img.addEventListener('error',function(){if(img.classList.contains('generated-poster'))return;const src=img.dataset.originalSrc||'';if(img.dataset.proxyTried&&!img.dataset.originalTried&&src){img.dataset.originalTried='true';img.src=src;return}if(!img.dataset.tmdbRetried&&/image\.tmdb\.org\/t\/p\/original\//.test(img.src)){img.dataset.tmdbRetried='true';img.src=img.src.replace('/original/','/w500/');return}applyGenerated(img,img.closest('.card'))})}
function fill(root=document){root.querySelectorAll('.card').forEach(card=>{const poster=card.querySelector('.poster');if(!poster)return;const title=(card.dataset.title||card.querySelector('h3')?.textContent||'').trim(),item=lookup(title),src=posterFor(item,title);if(src&&!poster.querySelector('img')){poster.classList.add('image-poster');const img=document.createElement('img');img.src=src;img.alt=(item?.t||title)+' poster';img.loading='lazy';poster.prepend(img)}if(!poster.querySelector('img'))makeFallback(card)});root.querySelectorAll('.image-poster img').forEach(bind)}
if(window.CINEVAULT_CATALOG_READY){window.CINEVAULT_CATALOG_READY.then(()=>fill()).catch(()=>fill())}else fill();
const observer=new MutationObserver(m=>{for(const x of m)for(const n of x.addedNodes)if(n.nodeType===1)fill(n)});if(document.body)observer.observe(document.body,{childList:true,subtree:true});
document.addEventListener('cinevault:catalogue-rendered',()=>fill());document.addEventListener('cinevault:home-rendered',()=>fill());
})();