const search=document.getElementById('search'),clear=document.getElementById('clear');
function filter(q){q=(q||'').trim().toLowerCase();document.querySelectorAll('.card').forEach(card=>{const text=((card.dataset.title||'')+' '+(card.dataset.tags||'')+' '+card.innerText).toLowerCase();card.style.display=!q||text.includes(q)?'':'none'});document.querySelectorAll('.section').forEach(section=>{const cards=[...section.querySelectorAll('.card')];if(cards.length)section.style.display=cards.some(c=>c.style.display!=='none')?'':'none'})}
function goSearch(q){location.href=q?'search.html?q='+encodeURIComponent(q):'search.html'}
if(search){search.addEventListener('input',e=>filter(e.target.value));search.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();goSearch(e.target.value)}});if(clear)clear.addEventListener('click',()=>{search.value='';filter('');search.focus()})}
document.querySelectorAll('[data-genre]').forEach(button=>button.addEventListener('click',e=>{e.preventDefault();const genre=button.dataset.genre||'';location.href='genre.html?genre='+encodeURIComponent(genre)}));
const modal=document.getElementById('modal'),modalInput=document.getElementById('modalInput');
function openModal(){if(!modal)return;modal.classList.add('open');modal.setAttribute('aria-hidden','false');if(modalInput){modalInput.value=search?search.value:'';modalInput.focus()}}
function closeSearchModal(){if(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}}
const openSearch=document.getElementById('openSearch'),heroSearch=document.getElementById('heroSearch'),closeModal=document.getElementById('closeModal');if(openSearch)openSearch.onclick=openModal;if(heroSearch)heroSearch.onclick=openModal;if(closeModal)closeModal.onclick=closeSearchModal;if(modal)modal.addEventListener('click',e=>{if(e.target===modal)closeSearchModal()});if(modalInput)modalInput.addEventListener('input',e=>{if(search)search.value=e.target.value});if(modalInput)modalInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();goSearch(e.target.value)}})
const menu=document.getElementById('menu'),mobileNav=document.getElementById('mobileNav');if(menu&&mobileNav)menu.addEventListener('click',()=>mobileNav.classList.toggle('open'));document.querySelectorAll('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>mobileNav&&mobileNav.classList.remove('open')));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSearchModal();if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();openModal()}});
function load(src,done){const s=document.createElement('script');s.src=src;s.onload=done;s.onerror=()=>console.warn('CineVault could not load '+src);document.head.appendChild(s)}
load('catalogue-data.js',()=>load('home-catalogue.js',()=>load('catalog-enhancements.js',()=>load('genre-rails.js',()=>load('poster-system.js')))));
